import type { CollectionItem } from "./types";

/** 开发环境预置 demo 数据（localStorage 为空时注入） */
export const MOCK_COLLECTION_SEED: CollectionItem[] = [
  {
    id: "seed-1",
    sku: "2811310229",
    name: "Xiaomi Smartphone Redmi 15 Rostest (EAC) 8/256 GB, black",
    photo_url: "https://ir-21.ozonru.cn/s3/multimedia-1-l/8376454785.jpg",
    product_url: "https://www.ozon.ru/product/2811310229",
    current_price: 36712.14,
    rating: 4.8,
    review_count: 1250,
    competitor_count: 39,
    sold_count: 62710,
    collection_name: "Redmi 15 跟卖候选",
    brand: "Xiaomi",
    seller_name: "Ozon",
    collected_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    source_platform: "OZON",
    source_view: "product",
    processing_status: "pending",
    tags: ["热销"],
    category_path_zh: "电子产品 / 智能手机 / 智能手机",
  },
  {
    id: "seed-2",
    sku: "1492227600",
    name: "斯维托复印纸，5张A4规格，500页",
    photo_url: null,
    product_url: "https://www.ozon.ru/product/1492227600",
    current_price: 3473.82,
    rating: 4.5,
    review_count: 320,
    competitor_count: 6,
    sold_count: 15200,
    collection_name: "办公用纸 1688 比价",
    brand: "Chappi",
    seller_name: "Ozon",
    collected_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    source_platform: "OZON",
    source_view: "category",
    processing_status: "created",
    tags: [],
    category_path_zh: "宠物用品 / 干粮",
  },
  {
    id: "seed-3",
    sku: "88880001",
    name: "1688 货源示例商品",
    photo_url: null,
    product_url: null,
    current_price: 89.5,
    rating: null,
    review_count: null,
    competitor_count: null,
    sold_count: null,
    collection_name: "1688 找货示例",
    brand: null,
    seller_name: "义乌供应商",
    collected_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    source_platform: "1688",
    source_view: "product",
    processing_status: "pending",
    tags: ["1688"],
    category_path_zh: null,
  },
];
