import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    screens: {
      sm: "375px",
      md: "768px",
      lg: "1024px",
      xl: "1440px",
    },
    colors: {
      // Brand — polarity-invariant (sentry/DESIGN.md)
      primary: "#150f23",
      "ink-deep": "#1f1633",
      "on-primary": "#ffffff",
      "accent-lime": "#c2ef4e",
      "accent-pink": "#fa7faa",
      "accent-violet": "#6a5fc1",
      "accent-violet-deep": "#422082",
      "accent-violet-mid": "#79628c",
      "ring-focus": "#9dc1f5",
      // Static surfaces
      "surface-canvas-dark": "#1f1633",
      "surface-canvas-light": "#ffffff",
      "surface-night": "#150f23",
      "surface-press-light": "#f0f0f0",
      "surface-press-stronger": "#efefef",
      "hairline-violet": "#362d59",
      "hairline-cool": "#cfcfdb",
      "hairline-cloud": "#e5e7eb",
      "on-dark-muted": "#bdb8c0",
      "on-dark-faint": "#3f3849",
      "ink-press": "#1a1a1a",
      // Theme-aware semantic tokens (CSS variables in globals.css)
      canvas: "var(--color-canvas)",
      "surface-card": "var(--color-surface-card)",
      "surface-elevated": "var(--color-surface-elevated)",
      ink: "var(--color-ink)",
      body: "var(--color-body)",
      muted: "var(--color-muted)",
      hairline: "var(--color-hairline)",
      "btn-primary-bg": "var(--color-btn-primary-bg)",
      "btn-primary-text": "var(--color-btn-primary-text)",
      "btn-primary-pressed-bg": "var(--color-btn-primary-pressed-bg)",
      "btn-primary-pressed-text": "var(--color-btn-primary-pressed-text)",
      "btn-ghost-bg": "var(--color-btn-ghost-bg)",
      "btn-ghost-text": "var(--color-btn-ghost-text)",
      // Semantic status
      success: "#34c759",
      warning: "#ff9500",
      error: "#ff3b30",
      white: "#ffffff",
      black: "#000000",
      transparent: "transparent",
      current: "currentColor",
    },
    fontSize: {
      "display-hero": ["88px", { lineHeight: "1.2", fontWeight: "700" }],
      "display-large": ["60px", { lineHeight: "1.1", fontWeight: "500" }],
      "heading-xl": ["30px", { lineHeight: "1.2", fontWeight: "500" }],
      "heading-lg": ["27px", { lineHeight: "1.25", fontWeight: "500" }],
      "heading-md": ["24px", { lineHeight: "1.25", fontWeight: "500" }],
      "heading-sm": ["20px", { lineHeight: "1.25", fontWeight: "600" }],
      "body-lg": ["16px", { lineHeight: "2.0", fontWeight: "400" }],
      "body-strong": ["16px", { lineHeight: "1.5", fontWeight: "600" }],
      body: ["16px", { lineHeight: "1.5", fontWeight: "500" }],
      eyebrow: ["15px", { lineHeight: "1.4", fontWeight: "500" }],
      "button-cap": [
        "14px",
        { lineHeight: "1.14", fontWeight: "700", letterSpacing: "0.2px" },
      ],
      "button-cap-light": [
        "14px",
        { lineHeight: "1.29", fontWeight: "500", letterSpacing: "0.2px" },
      ],
      caption: ["14px", { lineHeight: "1.43", fontWeight: "400" }],
      "micro-cap": [
        "10px",
        { lineHeight: "1.8", fontWeight: "600", letterSpacing: "0.25px" },
      ],
      code: ["16px", { lineHeight: "1.5", fontWeight: "400" }],
    },
    borderRadius: {
      none: "0",
      xs: "4px",
      sm: "6px",
      md: "8px",
      lg: "10px",
      xl: "12px",
      xxl: "18px",
      full: "9999px",
    },
    spacing: {
      xxs: "2px",
      xs: "4px",
      sm: "8px",
      md: "12px",
      lg: "16px",
      xl: "24px",
      xxl: "32px",
      section: "96px",
      0: "0",
      1: "4px",
      2: "8px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      8: "32px",
      10: "40px",
      12: "48px",
      16: "64px",
    },
    fontFamily: {
      display: ['"Space Grotesk"', "Rubik", "system-ui", "sans-serif"],
      text: ["Rubik", "system-ui", "-apple-system", "sans-serif"],
      mono: ["Monaco", "Menlo", "Ubuntu Mono", "ui-monospace", "monospace"],
    },
    boxShadow: {
      "level-1": "rgba(0,0,0,0.08) 0 2px 8px 0",
      "level-2":
        "rgba(0,0,0,0.1) 0 10px 15px -3px, rgba(0,0,0,0.1) 0 4px 6px -4px",
      "level-3": "rgb(21,15,35) 0 0 8px 6px",
      card: "var(--shadow-card)",
      none: "none",
    },
    extend: {
      transitionDuration: {
        DEFAULT: "200ms",
      },
    },
  },
  plugins: [],
};

export default config;
