import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      primary: '#0066cc',
      'primary-focus': '#0071e3',
      'primary-on-dark': '#2997ff',
      ink: '#1d1d1f',
      'ink-muted-80': '#333333',
      'ink-muted-48': '#7a7a7a',
      canvas: '#ffffff',
      'canvas-parchment': '#f5f5f7',
      'surface-tile-1': '#272729',
      'surface-tile-2': '#2a2a2c',
      'surface-black': '#000000',
      white: '#ffffff',
      black: '#000000',
      transparent: 'transparent',
      current: 'currentColor',
      red: '#ff3b30',
      orange: '#ff9500',
      yellow: '#ffcc00',
      green: '#34c759',
      teal: '#5ac8fa',
      blue: '#007aff',
      purple: '#af52de',
    },
    fontSize: {
      'hero-display': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px', fontWeight: '600' }],
      'display-lg': ['40px', { lineHeight: '1.1', fontWeight: '600' }],
      'display-md': ['32px', { lineHeight: '1.14', fontWeight: '600' }],
      'display-sm': ['28px', { lineHeight: '1.17', fontWeight: '600' }],
      'title': ['24px', { lineHeight: '1.25', fontWeight: '500' }],
      'body': ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '400' }],
      'body-sm': ['15px', { lineHeight: '1.47', fontWeight: '400' }],
      'caption': ['13px', { lineHeight: '1.38', fontWeight: '400' }],
      'caption-sm': ['11px', { lineHeight: '1.36', fontWeight: '400' }],
    },
    borderRadius: {
      none: '0',
      xs: '5px',
      sm: '8px',
      md: '11px',
      lg: '18px',
      pill: '9999px',
      full: '9999px',
    },
    spacing: {
      xxs: '4px',
      xs: '8px',
      sm: '12px',
      md: '17px',
      lg: '24px',
      xl: '32px',
      xxl: '48px',
      section: '80px',
      0: '0',
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      8: '32px',
      10: '40px',
      12: '48px',
      16: '64px',
    },
    fontFamily: {
      display: ['"SF Pro Display"', 'system-ui', '-apple-system', 'sans-serif'],
      text: ['"SF Pro Text"', 'system-ui', '-apple-system', 'sans-serif'],
      mono: ['"SF Mono"', 'Menlo', 'Monaco', 'monospace'],
    },
    extend: {
      backdropBlur: {
        frosted: '20px',
      },
    },
  },
  plugins: [],
};

export default config;
