"""initial

Revision ID: 1c2b0122e85d
Revises: 
Create Date: 2026-06-12 21:45:26.724228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c2b0122e85d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranked_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('sales_trend', sa.String(length=50), nullable=True),
    sa.Column('rank_type', sa.String(length=20), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranked_products_category'), 'ranked_products', ['category'], unique=False)
    op.create_index(op.f('ix_ranked_products_ozon_product_id'), 'ranked_products', ['ozon_product_id'], unique=False)
    op.create_index(op.f('ix_ranked_products_rank_type'), 'ranked_products', ['rank_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profit_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('collected_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ozon_product_id', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_zh', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('price_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('video_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_path', sa.String(length=500), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ozon_product_id', name='uq_user_ozon_product')
    )
    op.create_index(op.f('ix_collected_products_user_id'), 'collected_products', ['user_id'], unique=False)
    op.create_table('selected_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ranked_product_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ranked_product_id'], ['ranked_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_products_user_id'), 'selected_products', ['user_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ozon_client_id', sa.Text(), nullable=False),
    sa.Column('ozon_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_user_id'), 'stores', ['user_id'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collected_product_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seededit_task_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seededit_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=30), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collected_product_id'], ['collected_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_tasks_collected_product_id'), 'processing_tasks', ['collected_product_id'], unique=False)
    op.create_table('supply_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collected_product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('price_cny', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_product_id'], ['collected_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_sources_collected_product_id'), 'supply_sources', ['collected_product_id'], unique=False)
    op.create_table('profit_calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collected_product_id', sa.UUID(), nullable=False),
    sa.Column('supply_source_id', sa.UUID(), nullable=True),
    sa.Column('ozon_price_cny', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supply_cost_cny', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('logistics_cost_cny', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_product_id'], ['collected_products.id'], ),
    sa.ForeignKeyConstraint(['supply_source_id'], ['supply_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_calculations_collected_product_id'), 'profit_calculations', ['collected_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_calculations_collected_product_id'), table_name='profit_calculations')
    op.drop_table('profit_calculations')
    op.drop_index(op.f('ix_supply_sources_collected_product_id'), table_name='supply_sources')
    op.drop_table('supply_sources')
    op.drop_index(op.f('ix_processing_tasks_collected_product_id'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index(op.f('ix_stores_user_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_selected_products_user_id'), table_name='selected_products')
    op.drop_table('selected_products')
    op.drop_index(op.f('ix_collected_products_user_id'), table_name='collected_products')
    op.drop_table('collected_products')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ranked_products_rank_type'), table_name='ranked_products')
    op.drop_index(op.f('ix_ranked_products_ozon_product_id'), table_name='ranked_products')
    op.drop_index(op.f('ix_ranked_products_category'), table_name='ranked_products')
    op.drop_table('ranked_products')
    # ### end Alembic commands ###
